# Generated by Django 4.1.5 on 2023-01-24 08:27

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qcontent', ckeditor_uploader.fields.RichTextUploadingField()),
                ('questionname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='BPage.question')),
            ],
        ),
    ]
