# Generated by Django 4.1.5 on 2023-02-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPage', '0003_alter_devices_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='link',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
