# Generated by Django 4.2.3 on 2023-07-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BPage', '0004_devices_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='Topics',
        ),
    ]
