# Generated by Django 4.2.3 on 2023-07-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BPage', '0006_rename_topics_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='model',
            new_name='topic_name',
        ),
    ]
