# Generated by Django 4.2.3 on 2023-07-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BPage', '0007_rename_model_topic_topic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='modelname',
            new_name='topic_name',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('topic_name', 'Question')},
        ),
    ]
